"use client";

import React, { useState, useMemo } from "react";
import { Copy, Check, Type, Sparkles, Gamepad2, Hash } from "lucide-react";
import { Container } from "../Layout/Container";
import { JsonLd } from "../../lib/seo";
import Link from "next/link";

interface FontItem {
  name: string;
  category: string;
  transform: (text: string) => string;
}

const StylishFonts: React.FC = () => {
  const [input, setInput] = useState("");
  const [copiedIndex, setCopiedIndex] = useState<number | null>(null);
  const [category, setCategory] = useState("All");

  const handleCopy = (text: string, index: number) => {
    navigator.clipboard.writeText(text);
    setCopiedIndex(index);
    setTimeout(() => setCopiedIndex(null), 2000);
  };

  /* ======================
     FONT DATABASE (50+)
  =======================*/

  const baseDecorators = ["乂", "亗", "么", "々", "メ", "么", "๛", "⚔", "☬", "♛", "ঔ", "ঊ"];

  const fontMaps: FontItem[] = useMemo(() => {
    const unicodeBold: any = {
      a: "𝗮", b: "𝗯", c: "𝗰", d: "𝗱", e: "𝗲", f: "𝗳",
      g: "𝗴", h: "𝗵", i: "𝗶", j: "𝗷", k: "𝗸", l: "𝗹",
      m: "𝗺", n: "𝗻", o: "𝗼", p: "𝗽", q: "𝗾", r: "𝗿",
      s: "𝘀", t: "𝘁", u: "𝘂", v: "𝘃", w: "𝘄", x: "𝘅",
      y: "𝘆", z: "𝘇",
    };

    const transformMap = (text: string, map: any) =>
      text.split("").map(c => map[c.toLowerCase()] || c).join("");

    const styles: FontItem[] = [
      {
        name: "Bold Sans",
        category: "Professional",
        transform: (text) => transformMap(text, unicodeBold),
      },
      {
        name: "PUBG King",
        category: "Gaming",
        transform: (text) => `乂 ${text} 乂`,
      },
      {
        name: "Free Fire Elite",
        category: "Gaming",
        transform: (text) => `亗 ${text} 亗`,
      },
      {
        name: "Shadow Clan",
        category: "Gaming",
        transform: (text) => `☬ ${text} ☬`,
      },
      {
        name: "Crown Style",
        category: "Gaming",
        transform: (text) => `♛ ${text} ♛`,
      },
      {
        name: "Fire Gamer",
        category: "Gaming",
        transform: (text) => `🔥 ${text} 🔥`,
      },
      {
        name: "Cute Hearts",
        category: "Cute",
        transform: (text) => `💖 ${text} 💖`,
      },
      {
        name: "Aesthetic Stars",
        category: "Decorative",
        transform: (text) => `✦ ${text} ✦`,
      },
    ];

    // Generate 40+ additional gaming variants
    for (let i = 0; i < 40; i++) {
      styles.push({
        name: `Gaming Variant ${i + 1}`,
        category: "Gaming",
        transform: (text: string) =>
          `${baseDecorators[i % baseDecorators.length]} ${text} ${baseDecorators[i % baseDecorators.length]}`,
      });
    }

    return styles;
  }, []);

  const categories = ["All", "Gaming", "Professional", "Cute", "Decorative"];

  const filteredFonts =
    category === "All"
      ? fontMaps
      : fontMaps.filter((f) => f.category === category);

  /* ======================
     TOP 100 PUBG NAMES
  =======================*/

  const pubgNames = [
    "乂ShadowKing乂", "亗DarkHunter亗", "♛RoyalSniper♛", "☬GhostRider☬",
    "乂VenomX乂", "亗ToxicPro亗", "♛BulletMaster♛", "☬NoMercy☬",
    "乂AlphaBeast乂", "亗HeadshotPro亗"
  ];

  const faqs = [
    {
      q: "Can I use these stylish fonts directly on Instagram?",
      a: "Yes, absolutely. The text generated by our tool is created using universal Unicode mathematical and alphabetical symbols. You can copy and paste these unique fonts directly into your Instagram bio, username field, or captions without any formatting issues."
    },
    {
      q: "Are these gaming symbols safe to use in PUBG and Free Fire?",
      a: "Yes. Using Unicode characters like 乂, 亗, or ☬ in mobile games like PUBG (BGMI), Free Fire, or Call of Duty Mobile is 100% safe. They are globally recognized text symbols, not third-party hacks or modded scripts, meaning your gaming account cannot be banned for using them."
    },
    {
      q: "Why do some font symbols show up as blank boxes?",
      a: "If a symbol appears as a blank square or question mark (often called 'tofu'), it means the device or the app you are pasting it into does not support that specific extended Unicode set. Try selecting a simpler 'Professional' font category if this occurs."
    },
    {
      q: "Does changing my font affect SEO or searchability?",
      a: "Yes, it can. While stylish fonts look amazing in a bio, you should avoid using them for your main searchable Name or Title. Search engines and platform algorithms cannot easily read Unicode symbols like '𝗯𝗼𝗹𝗱 𝘁𝗲𝘅𝘁'. Use them for aesthetic decoration, not for primary keywords."
    }
  ];

  return (
    <>
      <JsonLd
        type="SoftwareApplication"
        data={{
          name: "Stylish Font Generator",
          applicationCategory: "Utility",
          operatingSystem: "Web",
          offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
          description: "Generate PUBG, Free Fire, Instagram stylish names using 50+ Unicode fonts for free."
        }}
      />

      <JsonLd
        type="FAQPage"
        data={{
          "@context": "https://schema.org",
          "@type": "FAQPage",
          mainEntity: faqs.map(faq => ({
            "@type": "Question",
            name: faq.q,
            acceptedAnswer: {
              "@type": "Answer",
              text: faq.a
            }
          }))
        }}
      />

      <Container className="py-16 md:py-24 space-y-20">
        <header className="text-center space-y-6 max-w-4xl mx-auto">
          <h1 className="text-4xl md:text-5xl lg:text-6xl font-black text-foreground tracking-tight leading-tight">
            Stylish Font Generator
            <br className="hidden md:block" />
            <span className="text-primary text-3xl md:text-5xl">For PUBG, IG & Social Media</span>
          </h1>
          <p className="text-muted-foreground text-lg md:text-xl leading-relaxed max-w-2xl mx-auto">
            Create unique gaming names, aesthetic Instagram bios, and stylish nicknames instantly using our powerful Unicode engine.
          </p>
        </header>

        <div className="max-w-3xl mx-auto space-y-6">
          <div className="relative group">
            <Type className="absolute left-5 top-1/2 -translate-y-1/2 w-6 h-6 text-primary transition-transform group-focus-within:scale-110" />
            <input
              type="text"
              placeholder="Enter your name or text here..."
              value={input}
              onChange={(e) => setInput(e.target.value)}
              className="w-full pl-14 pr-4 py-5 border-2 border-border rounded-2xl bg-background text-foreground focus:border-primary focus:ring-4 focus:ring-primary/20 outline-none text-lg shadow-sm transition-all"
            />
          </div>

          <div className="flex flex-wrap gap-2 justify-center">
            {categories.map((cat) => (
              <button
                key={cat}
                onClick={() => setCategory(cat)}
                className={`px-5 py-2 rounded-xl text-sm font-semibold transition-all ${category === cat
                    ? "bg-primary text-white shadow-md shadow-primary/20 scale-105"
                    : "bg-muted text-muted-foreground hover:bg-muted/80"
                  }`}
              >
                {cat}
              </button>
            ))}
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 max-w-5xl mx-auto min-h-[400px]">
          {input.trim() === "" ? (
            <div className="col-span-full flex flex-col items-center justify-center py-20 border-2 border-dashed border-border rounded-3xl text-muted-foreground bg-card/50">
              <Sparkles className="w-12 h-12 mb-4 text-primary/30" />
              <p className="text-lg">Type something above to generate stylish fonts.</p>
            </div>
          ) : (
            filteredFonts.map((font, idx) => {
              const transformed = font.transform(input);
              return (
                <div
                  key={idx}
                  className="bg-card border border-border hover:border-primary/40 rounded-xl p-5 flex justify-between items-center transition-all shadow-sm"
                >
                  <div className="overflow-hidden pr-4">
                    <p className="text-xs font-semibold text-primary/80 mb-1 uppercase tracking-wider">
                      {font.name}
                    </p>
                    <p className="text-xl text-foreground truncate">
                      {transformed}
                    </p>
                  </div>
                  <button
                    onClick={() => handleCopy(transformed, idx)}
                    className="p-3 bg-muted hover:bg-primary/10 hover:text-primary rounded-lg transition-colors shrink-0"
                    aria-label="Copy text"
                  >
                    {copiedIndex === idx ? (
                      <Check className="w-5 h-5 text-green-500" />
                    ) : (
                      <Copy className="w-5 h-5" />
                    )}
                  </button>
                </div>
              );
            })
          )}
        </div>

        <section className="max-w-4xl mx-auto space-y-6 bg-card border border-border p-8 rounded-3xl">
          <div className="flex items-center gap-3 mb-6">
            <Gamepad2 className="w-6 h-6 text-primary" />
            <h2 className="text-2xl font-bold text-foreground m-0">
              Top Trending PUBG & BGMI Names
            </h2>
          </div>
          <ul className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3 text-muted-foreground">
            {pubgNames.map((name, i) => (
              <li key={i} className="bg-background border border-border rounded-xl p-3 text-center hover:border-primary/30 transition-colors font-medium cursor-default">
                {name}
              </li>
            ))}
          </ul>
        </section>

        {/* ================= IN-DEPTH ADSENSE ARTICLE ================= */}
        <section className="max-w-5xl mx-auto mt-24 space-y-20 border-t border-border pt-20">
          <div className="space-y-16">

            <div className="space-y-6 text-center md:text-left">
              <h2 className="text-3xl md:text-4xl font-extrabold tracking-tight text-foreground flex items-center md:justify-start justify-center gap-3">
                <Hash className="w-8 h-8 text-primary" />
                The Ultimate Guide to Unicode Font Generation
              </h2>
              <p className="text-muted-foreground leading-relaxed text-base md:text-lg max-w-4xl mx-auto md:mx-0">
                LinkGen's Advanced Stylish Font Generator is engineered to help gamers, content creators, and social media influencers craft high-impact digital identities. Whether you are generating a hardcore clan name for PUBG Mobile, an aesthetic bio for Instagram, or a professional username for Discord, our tool uses 50+ Unicode-powered styles to bypass standard keyboard limitations.
              </p>
            </div>

            <div className="grid md:grid-cols-2 gap-12 items-start">
              <div className="space-y-6">
                <h3 className="text-2xl font-bold text-foreground">
                  Why Stylish Fonts Matter in 2026
                </h3>
                <p className="text-muted-foreground leading-relaxed">
                  In massive multiplayer online games (MMOs) and highly competitive social networks, your username is your first impression. Standard alphabets easily get lost in the noise. By utilizing specialized symbols like <strong>乂, 亗, ☬, and ♛</strong>, you instantly signal clan identity, experience, and authority.
                </p>
                <p className="text-muted-foreground leading-relaxed">
                  On visual platforms like Instagram and TikTok, utilizing a bold or aesthetic font in your bio acts as a "pattern interrupt," drastically increasing the scroll-stopping power of your profile and improving follower conversion rates.
                </p>
              </div>

              <div className="bg-muted/40 border border-border rounded-3xl p-8 space-y-4">
                <h4 className="font-bold text-foreground text-xl">
                  The Technology: How it Works
                </h4>
                <p className="text-base text-muted-foreground leading-relaxed">
                  Our tool does not actually generate new "fonts" in the traditional sense (like Arial or Times New Roman). Instead, it maps your standard keyboard characters into <strong>Unicode Mathematical and Alphanumeric Symbols</strong>. Because these are recognized globally as standard text characters rather than custom font files, they render perfectly across Android, iOS, Windows, and macOS without requiring the viewer to install any third-party applications.
                </p>
              </div>
            </div>

            <div className="space-y-8">
              <h3 className="text-2xl font-bold text-foreground">
                Top Use Cases for the Font Generator
              </h3>
              <div className="grid md:grid-cols-3 gap-6">
                <div className="bg-card border border-border p-6 rounded-2xl">
                  <h4 className="font-bold text-primary mb-2">1. Mobile Gaming</h4>
                  <p className="text-sm text-muted-foreground">Perfect for generating unique "Rename Card" tags in BGMI, Free Fire, and Valorant without triggering the "Name Already Taken" error.</p>
                </div>
                <div className="bg-card border border-border p-6 rounded-2xl">
                  <h4 className="font-bold text-primary mb-2">2. Social Media Bios</h4>
                  <p className="text-sm text-muted-foreground">Make your Linktree, Instagram, or Twitter profile stand out by using sleek, minimalist, or bold typography to highlight your profession.</p>
                </div>
                <div className="bg-card border border-border p-6 rounded-2xl">
                  <h4 className="font-bold text-primary mb-2">3. Discord Servers</h4>
                  <p className="text-sm text-muted-foreground">Format your Discord channel names, role titles, and personal nickname to create a highly aesthetic and organized community server.</p>
                </div>
              </div>
            </div>

            <div className="space-y-6">
              <h3 className="text-2xl font-bold text-foreground">
                Standard Text vs Unicode Symbols
              </h3>
              <div className="overflow-x-auto border border-border rounded-2xl shadow-sm">
                <table className="w-full text-base">
                  <thead className="bg-muted text-foreground">
                    <tr>
                      <th className="text-left px-6 py-4 font-bold">Feature Comparison</th>
                      <th className="text-left px-6 py-4 font-bold">Standard Keyboard</th>
                      <th className="text-left px-6 py-4 font-bold text-primary">Unicode Fonts</th>
                    </tr>
                  </thead>
                  <tbody className="text-muted-foreground bg-card">
                    <tr className="border-t border-border">
                      <td className="px-6 py-4 font-medium text-foreground">Visual Impact & Branding</td>
                      <td className="px-6 py-4">Basic / Generic</td>
                      <td className="px-6 py-4 text-primary font-semibold">High / Aesthetic</td>
                    </tr>
                    <tr className="border-t border-border">
                      <td className="px-6 py-4 font-medium text-foreground">Availability of Names</td>
                      <td className="px-6 py-4">Mostly Taken</td>
                      <td className="px-6 py-4">Always Unique</td>
                    </tr>
                    <tr className="border-t border-border">
                      <td className="px-6 py-4 font-medium text-foreground">Gaming Symbol Support</td>
                      <td className="px-6 py-4">None</td>
                      <td className="px-6 py-4">50+ Clan Symbols</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>

            <div className="space-y-8 pt-8 border-t border-border">
              <h3 className="text-2xl font-bold text-foreground">
                Frequently Asked Questions (FAQ)
              </h3>
              <div className="grid md:grid-cols-2 gap-6">
                {faqs.map((faq, i) => (
                  <div
                    key={i}
                    className="bg-card border border-border rounded-2xl p-6 space-y-3 hover:border-primary/30 transition-colors"
                  >
                    <div className="flex items-start gap-3">
                      <div className="mt-1 flex-shrink-0 w-6 h-6 bg-primary/10 text-primary rounded flex items-center justify-center text-xs font-bold">
                        Q
                      </div>
                      <p className="font-bold text-foreground">{faq.q}</p>
                    </div>
                    <p className="text-muted-foreground text-sm leading-relaxed pl-9">
                      {faq.a}
                    </p>
                  </div>
                ))}
              </div>
            </div>

            <div className="bg-primary/5 border border-primary/20 rounded-3xl p-10 text-center space-y-6">
              <h3 className="text-2xl font-bold text-foreground">
                Explore More Creator Tools
              </h3>
              <p className="text-muted-foreground">Boost your workflow with our suite of free utilities.</p>
              <div className="flex flex-wrap justify-center gap-4">
                <Link
                  href="/character-counter"
                  className="px-6 py-3 bg-background border-2 border-border rounded-xl hover:border-primary hover:text-primary transition-all font-semibold shadow-sm"
                >
                  Bio Character Counter
                </Link>
                <Link
                  href="/instagram-bio-generator"
                  className="px-6 py-3 bg-background border-2 border-border rounded-xl hover:border-primary hover:text-primary transition-all font-semibold shadow-sm"
                >
                  Instagram Bio Generator
                </Link>
                <Link
                  href="/youtube-tag-extractor"
                  className="px-6 py-3 bg-background border-2 border-border rounded-xl hover:border-primary hover:text-primary transition-all font-semibold shadow-sm"
                >
                  YouTube Tag Extractor
                </Link>
              </div>
            </div>

          </div>
        </section>
      </Container>
    </>
  );
};

export default StylishFonts;